export const USERS = [
  {
    id: 55660,
    name: 'John',
    surname: 'Doe',
    address: '1234 Main St',
    email: 'johndoe@gmail.com',
    password: '123456',
    image: 'https://avatar.iran.liara.run/public/12',
    role: { id: 1, name: 'Admin' },
  },
  {
    id: 3685,
    name: 'Jane',
    surname: 'Doe',
    address: '1234 Main St',
    email: 'janedoe@gmail.com',
    password: '654321',
    image: 'https://avatar.iran.liara.run/public/45',
    role: { id: 2, name: 'User' },
  },
  {
    id: 12034,
    name: 'Alice',
    surname: 'Smith',
    address: '5678 Oak St',
    email: 'alicesmith@gmail.com',
    password: 'password123',
    image: 'https://avatar.iran.liara.run/public/64',
    role: { id: 2, name: 'User' },
  },
  {
    id: 78291,
    name: 'Bob',
    surname: 'Johnson',
    address: '9101 Pine St',
    email: 'bobjohnson@gmail.com',
    password: 'securepwd',
    image: 'https://avatar.iran.liara.run/public/23',
    role: { id: 1, name: 'Admin' },
  },
  {
    id: 39483,
    name: 'Charlie',
    surname: 'Brown',
    address: '112 Maple St',
    email: 'charliebrown@gmail.com',
    password: 'letmein',
    image: 'https://avatar.iran.liara.run/public/54',
    role: { id: 2, name: 'User' },
  },
  {
    id: 50832,
    name: 'Daisy',
    surname: 'Miller',
    address: '345 Birch St',
    email: 'daisymiller@gmail.com',
    password: 'daisypwd',
    image: 'https://avatar.iran.liara.run/public/33',
    role: { id: 2, name: 'User' },
  },
  {
    id: 67543,
    name: 'Ethan',
    surname: 'Williams',
    address: '789 Cedar St',
    email: 'ethanwilliams@gmail.com',
    password: 'passw0rd',
    image: 'https://avatar.iran.liara.run/public/35',
    role: { id: 2, name: 'User' },
  },
  {
    id: 93021,
    name: 'Fiona',
    surname: 'Garcia',
    address: '234 Spruce St',
    email: 'fionagarcia@gmail.com',
    password: 'fionapass',
    image: 'https://avatar.iran.liara.run/public/36',
    role: { id: 1, name: 'Admin' },
  },
  {
    id: 21394,
    name: 'George',
    surname: 'Harris',
    address: '678 Ash St',
    email: 'georgeharris@gmail.com',
    password: 'mypassword',
    image: 'https://avatar.iran.liara.run/public/38',
    role: { id: 2, name: 'User' },
  },
  {
    id: 48765,
    name: 'Hannah',
    surname: 'Martinez',
    address: '901 Walnut St',
    email: 'hannahmartinez@gmail.com',
    password: 'hannahpwd',
    image: 'https://avatar.iran.liara.run/public/39',
    role: { id: 2, name: 'User' },
  },
];
